[project]
name = "first-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.46.1",
]

[tool.uv.workspace]
members = [
    "first-streamlit",
]
